package io.ctl.auth;

import com.google.gson.Gson;

import org.apache.http.HttpClientConnection;
import org.apache.http.HttpRequest;
import org.apache.http.HttpResponse;
import org.apache.http.HttpVersion;
import org.apache.http.StatusLine;
import org.apache.http.entity.ByteArrayEntity;
import org.apache.http.message.BasicHttpResponse;
import org.apache.http.message.BasicStatusLine;
import org.apache.http.protocol.HttpContext;
import org.apache.http.protocol.HttpRequestExecutor;

public class TestProcessor extends HttpRequestExecutor {

    String token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IjlVWkZXbWVXeHBrN28xajliSk1LMFV1VE9IVGtWNURVVThvd19nMGxhQjgiLCJhbGciOiJSUzI1NiIsIng1dCI6ImFQY3R3X29kdlJPb0VOZzNWb09sSWgydGlFcyIsImtpZCI6ImFQY3R3X29kdlJPb0VOZzNWb09sSWgydGlFcyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmIxNzExNS05OTE1LTQyYzAtOWYxYi00Zjk4ZTVhNGJjZDIvIiwiaWF0IjoxNTcwNzE0NDQwLCJuYmYiOjE1NzA3MTQ0NDAsImV4cCI6MTU3MDcxODM0MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhOQUFBQUk3ZEN1L2QwSE96emVDU0d3MnI3OGYzWloycC9vUThTTTkydzJmR2YrK2lUcUVJS1dzTU1DZWNQdWJhLzVoWDVLTVVsNDdLcjZ0M01BUWpEWTBLQVFpamxlZTRuNWdzMXBLSkxrYzJNRkZVPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiWHRyYW5ldCIsImFwcGlkIjoiZjkwNjgxZWEtNTNhOS00YTZkLWE5OGUtYWFhNjNlNTQzNjVmIiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJTY2h3YWIiLCJnaXZlbl9uYW1lIjoiQnJhZGxleSIsImlwYWRkciI6IjE1Ny4xMzAuMTcxLjQ2IiwibmFtZSI6IlNjaHdhYiwgQnJhZGxleSIsIm9pZCI6ImMzYzQwNGFkLTRlNGItNGZmOS1iNTI0LWZkY2Q2NTZmZmRmNiIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xMjMzNDA4NTkxLTYzMjU2NTg4OS0yODYxOTY0MjM5LTEwOTE3NTMzIiwicGxhdGYiOiI1IiwicHVpZCI6IjEwMDMzRkZGOUVGODlFQ0QiLCJzY3AiOiJlbWFpbCBvcGVuaWQgcHJvZmlsZSBTaXRlcy5SZWFkLkFsbCBVc2VyLlJlYWQiLCJzdWIiOiJJMjl6MHhfMk0zS24yMGhMNGd4TDkwMWNOcFduTVVhMmJ5aWRPRmhhT0xjIiwidGlkIjoiNzJiMTcxMTUtOTkxNS00MmMwLTlmMWItNGY5OGU1YTRiY2QyIiwidW5pcXVlX25hbWUiOiJCcmFkbGV5LlNjaHdhYkBDZW50dXJ5TGluay5jb20iLCJ1cG4iOiJCcmFkbGV5LlNjaHdhYkBDZW50dXJ5TGluay5jb20iLCJ1dGkiOiJ5a0gyampsMUUwMno4UmtXVXM0WUFBIiwidmVyIjoiMS4wIiwieG1zX3N0Ijp7InN1YiI6IlhKMWtTOFJKMTczTkE4MUtWdG5FZ01wc0loU0xqbm52Q0VTUlVQcGZxSFkifSwieG1zX3RjZHQiOjE0MjEwOTk2MzZ9.WDqGgREIsAB1UZPJ-L5HVUubZHIMArjtTDo6qCOIjgWjDJSbmpDUnDISOcts9mjvuh4NMZjMvSZg7r6P4RAbiKRYofZ5TNEKDuQdoMvYfJxFx25uq8BEmVxt3pQYgM-afow4HNC97oN4fXKXKpw3J1cFnueA7w2Zixt34fRuAO9O8N5nhY1uE0TcqjDzfJQMhLvrNjQrJtKc4L0tqkGoU9WGm2e3CmAzqD9cu3I2Wf4WTx1N5vx6VibI9rCQAoDueb7qp83A8ReRwlclqud1DekXc3mt5KuInK0CQeLZmVnBz53wIBz-5T6VV3WQTGuJYp3uXHPutAdALgb2XLAt3g";

    @Override
    public HttpResponse execute(HttpRequest request, HttpClientConnection conn, HttpContext context) {

        
        Gson gson = new Gson();
        String jsonBack = gson.toJson(new ResponseJson());

        StatusLine statusLine = new BasicStatusLine(HttpVersion.HTTP_1_1, 200, "OK");
        BasicHttpResponse response = new BasicHttpResponse(statusLine);
        response.setEntity(new ByteArrayEntity(jsonBack.getBytes()));
        return response;
    }


    private class ResponseJson {
        public String access_token = token;
    }
}